/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDesignsRouteImport } from './routes/admin.designs'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMassutskickRouteImport } from './routes/admin.massutskick'
import { Route as AdminMinTidrapportRouteImport } from './routes/admin.min-tidrapport'
import { Route as AdminMinaProjektRouteImport } from './routes/admin.mina-projekt'
import { Route as AdminMittSchemaRouteImport } from './routes/admin.mitt-schema'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminSchemaRouteImport } from './routes/admin.schema'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminTillganglighetRouteImport } from './routes/admin.tillganglighet'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignsRoute = AdminDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMassutskickRoute = AdminMassutskickRouteImport.update({
  id: '/massutskick',
  path: '/massutskick',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinTidrapportRoute = AdminMinTidrapportRouteImport.update({
  id: '/min-tidrapport',
  path: '/min-tidrapport',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinaProjektRoute = AdminMinaProjektRouteImport.update({
  id: '/mina-projekt',
  path: '/mina-projekt',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMittSchemaRoute = AdminMittSchemaRouteImport.update({
  id: '/mitt-schema',
  path: '/mitt-schema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchemaRoute = AdminSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTillganglighetRoute = AdminTillganglighetRouteImport.update({
  id: '/tillganglighet',
  path: '/tillganglighet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/massutskick': typeof AdminMassutskickRoute
  '/admin/min-tidrapport': typeof AdminMinTidrapportRoute
  '/admin/mina-projekt': typeof AdminMinaProjektRoute
  '/admin/mitt-schema': typeof AdminMittSchemaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tillganglighet': typeof AdminTillganglighetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/massutskick': typeof AdminMassutskickRoute
  '/admin/min-tidrapport': typeof AdminMinTidrapportRoute
  '/admin/mina-projekt': typeof AdminMinaProjektRoute
  '/admin/mitt-schema': typeof AdminMittSchemaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tillganglighet': typeof AdminTillganglighetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/massutskick': typeof AdminMassutskickRoute
  '/admin/min-tidrapport': typeof AdminMinTidrapportRoute
  '/admin/mina-projekt': typeof AdminMinaProjektRoute
  '/admin/mitt-schema': typeof AdminMittSchemaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tillganglighet': typeof AdminTillganglighetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/designs'
    | '/admin/leads'
    | '/admin/massutskick'
    | '/admin/min-tidrapport'
    | '/admin/mina-projekt'
    | '/admin/mitt-schema'
    | '/admin/projects'
    | '/admin/schema'
    | '/admin/staff'
    | '/admin/tillganglighet'
    | '/admin/timesheets'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/designs'
    | '/admin/leads'
    | '/admin/massutskick'
    | '/admin/min-tidrapport'
    | '/admin/mina-projekt'
    | '/admin/mitt-schema'
    | '/admin/projects'
    | '/admin/schema'
    | '/admin/staff'
    | '/admin/tillganglighet'
    | '/admin/timesheets'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/designs'
    | '/admin/leads'
    | '/admin/massutskick'
    | '/admin/min-tidrapport'
    | '/admin/mina-projekt'
    | '/admin/mitt-schema'
    | '/admin/projects'
    | '/admin/schema'
    | '/admin/staff'
    | '/admin/tillganglighet'
    | '/admin/timesheets'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/designs': {
      id: '/admin/designs'
      path: '/designs'
      fullPath: '/admin/designs'
      preLoaderRoute: typeof AdminDesignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/massutskick': {
      id: '/admin/massutskick'
      path: '/massutskick'
      fullPath: '/admin/massutskick'
      preLoaderRoute: typeof AdminMassutskickRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/min-tidrapport': {
      id: '/admin/min-tidrapport'
      path: '/min-tidrapport'
      fullPath: '/admin/min-tidrapport'
      preLoaderRoute: typeof AdminMinTidrapportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mina-projekt': {
      id: '/admin/mina-projekt'
      path: '/mina-projekt'
      fullPath: '/admin/mina-projekt'
      preLoaderRoute: typeof AdminMinaProjektRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mitt-schema': {
      id: '/admin/mitt-schema'
      path: '/mitt-schema'
      fullPath: '/admin/mitt-schema'
      preLoaderRoute: typeof AdminMittSchemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schema': {
      id: '/admin/schema'
      path: '/schema'
      fullPath: '/admin/schema'
      preLoaderRoute: typeof AdminSchemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tillganglighet': {
      id: '/admin/tillganglighet'
      path: '/tillganglighet'
      fullPath: '/admin/tillganglighet'
      preLoaderRoute: typeof AdminTillganglighetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDesignsRoute: typeof AdminDesignsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMassutskickRoute: typeof AdminMassutskickRoute
  AdminMinTidrapportRoute: typeof AdminMinTidrapportRoute
  AdminMinaProjektRoute: typeof AdminMinaProjektRoute
  AdminMittSchemaRoute: typeof AdminMittSchemaRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSchemaRoute: typeof AdminSchemaRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTillganglighetRoute: typeof AdminTillganglighetRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDesignsRoute: AdminDesignsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMassutskickRoute: AdminMassutskickRoute,
  AdminMinTidrapportRoute: AdminMinTidrapportRoute,
  AdminMinaProjektRoute: AdminMinaProjektRoute,
  AdminMittSchemaRoute: AdminMittSchemaRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSchemaRoute: AdminSchemaRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTillganglighetRoute: AdminTillganglighetRoute,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
